version: "3"


services:
  webhook:
    build:
      context: .
      dockerfile: ./src/api.Dockerfile
    command: python3 /app/src/api_main.py
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - db:${DATA_FOLDER_PATH}

  bot:
    build:
      context: .
      dockerfile: ./src/bot.Dockerfile
    command: python3 /app/src/bot_main.py
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - db:${DATA_FOLDER_PATH}

  dbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - dbeaver:/opt/cloudbeaver/workspace
      - db:${DATA_FOLDER_PATH}

volumes:
  db:
  dbeaver:
